// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rs-splash/IPhoneSplash.tsx": () => import("../components/mockups/rs-splash/IPhoneSplash.tsx")
};
